name: Cachix build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  omikuji-unwrapped:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: omikuji-claymorwan-test # omikuji
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN_TEST }}'

      - name: Build omikuji-unwrapped
        run: nix build .#omikuji-unwrapped
        
      - run: nix run .#omikuji-unwrapped -- --version
